# Generated by Django 4.2.7 on 2024-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField(choices=[(0, '已禁用'), (1, '已启用')], default=1)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
