# Generated by Django 4.2.7 on 2024-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='permIds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
