# Generated by Django 4.2.7 on 2024-02-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='凭证')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '禁用')], default=1, verbose_name='用户状态')),
                ('role', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '超级管理员')], default=1, verbose_name='用户角色')),
                ('moreDetail', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01_index.user')),
            ],
        ),
    ]
