# Generated by Django 4.2.7 on 2024-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_index', '0002_alter_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
