# Generated by Django 4.2.7 on 2024-02-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01_index', '0002_alter_userinfo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('departName', models.CharField(max_length=32)),
                ('departCode', models.CharField(max_length=32)),
                ('manageName', models.CharField(max_length=32)),
                ('introduce', models.CharField(max_length=255)),
                ('manageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01_index.userinfo')),
            ],
        ),
    ]
