# Generated by Django 4.2.7 on 2024-02-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
