# Generated by Django 4.2.7 on 2024-03-01 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app03_department', '0002_alter_depart_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('phone_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=32)),
                ('workNumber', models.CharField(max_length=32)),
                ('timeOfEntry', models.DateField()),
                ('departmentName', models.CharField(blank=True, max_length=32, null=True)),
                ('formOfEmployment', models.SmallIntegerField(choices=[(1, '正式'), (2, '非正式')], default=1)),
                ('staffPhoto', models.CharField(blank=True, max_length=256, null=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03_department.depart')),
            ],
        ),
    ]
