# Generated by Django 4.2.7 on 2024-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名称')),
                ('description', models.CharField(max_length=64, verbose_name='权限描述')),
                ('type', models.IntegerField()),
                ('code', models.CharField(max_length=32, verbose_name='权限标识符')),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
